### ISSUE TITLE
Add polls from April 2021 Pew piece

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/polls#14]
https://www.pewresearch.org/global/2021/04/22/many-in-western-europe-and-u-s-want-economic-changes-as-pandemic-continues/

![image](https://user-images.githubusercontent.com/6076111/121225841-c8f59f80-c83e-11eb-8428-e61fd75267bf.png)

Add as four separate polls based on the Fall 2020 polls listed in https://www.pewresearch.org/methodology/international-survey-research/international-methodology/all-survey/france/all-year (and similarly for other countries)

Skip the below split, which doesn't fit with our data structure.
![image](https://user-images.githubusercontent.com/6076111/121226127-0fe39500-c83f-11eb-97fc-34718fe24ea6.png)

**Comment by CharlesBauman31** [comment]
OK, I have added the data into the Google Sheets. Again I haven't uploaded it to Github (combination of unsure how to do and not wanting to mess anything up!).

**Comment by MaxGhenis** [comment]
@kvanalebeek could you verify this one and upload to the CSVs if it hasn't been?

**Comment by kvanalebeek** [comment]
done!
