### ISSUE TITLE
Add data sheet mapping region to macro-region with population

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/polls#15]
This will enable us to perform weighted averages across multiple polls, since e.g. some polls combine `South East` and `South West` into `South` in UK polls. The sheet should have three columns: region, macro region, population.

**Comment by CharlesBauman31** [comment]
[https://docs.google.com/spreadsheets/d/1Fwn5lQqTkLCFNAxMAeElBaiURJcYULTxX8nwtteW49M/edit#gid=1314375233](url)

**Comment by CharlesBauman31** [comment]
I've put the information in a Google Sheets doc. I'm not sure how to upload anything to Github, and I'm not sure where we want this data to go.

**Comment by MaxGhenis** [comment]
Thanks @CharlesBauman31, I added that data to [this tab](https://docs.google.com/spreadsheets/d/1ulqohI6YLYFsz3wm8f5j6BS_JVelu2Ea8SXXa-wwkhQ/edit#gid=34524923) of the main poll tracking spreadsheet, formatted for easier merging.

For record-keeping I'll note your source here: https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/bulletins/annualmidyearpopulationestimates/latest
