### ISSUE TITLE
add poll #5 and #14 

### ISSUE THREAD

**Issue by kvanalebeek** [UBICenter/polls#16]
removing blanks from sheet to test dolthub, but should add back in

**Comment by MaxGhenis** [comment]
Moved to dolthub https://www.dolthub.com/repositories/ubicenter/polls/issues/2 and https://www.dolthub.com/repositories/ubicenter/polls/issues/3

**Comment by kvanalebeek** [comment]
<img width="928" alt="Screen Shot 2021-07-05 at 22 57 27" src="https://user-images.githubusercontent.com/77984871/124549939-c4dc8380-dde4-11eb-817e-7695102665a7.png">
added poll #5, hoping to get to #14 tomorrow
