### ISSUE TITLE
Add missing demographic info in Polls table

### ISSUE THREAD

**Issue by fedderw** [UBICenter/polls#60]
See the highlighted: 
![image](https://user-images.githubusercontent.com/16396180/133154745-e45430a2-51ab-4f3a-b433-63f18c21d29e.png)

I had forgotten about it before, but the distinction between, say, all adults and likely voters are important enough to warrant inclusion in the app.  My guess is that info is available somewhere, even if not at our original URL.

**Comment by kvanalebeek** [comment]
Added!
