### ISSUE TITLE
Correct Dalia Research EU28 poll responses + URL for 2016 

### ISSUE THREAD

**Issue by fedderw** [UBICenter/polls#63]
![image](https://user-images.githubusercontent.com/16396180/133156988-f8279dd6-7773-406a-a568-0e84b6e038a5.png)

![image](https://user-images.githubusercontent.com/16396180/133157062-3b080716-f146-48c1-986b-190ec96b2d9d.png)

**Comment by fedderw** [comment]
@kvanalebeek It looks like the 2016 poll info is a duplicate of 2017

**Comment by kvanalebeek** [comment]
I think I fixed it! Will confirm in check-in, but calculated 2016 values based on the 2017 values and the "percent changed" on slide 5 of 12
